---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: _data/site-settings.yml
  label: Site Settings
  match: "**/*"
- type: document
  path: _data/featured_work.yml
  label: Featured Projects
- type: directory
  path: _pages
  label: Pages
  create: documents
  match: "**/*"
- type: directory
  path: _catalog
  label: Work
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Journal
  create: all
- type: document
  path: _data/career_positions.yml
  label: Careers
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
