---
label: BLOCK-META
hide_body: true
display_field: layout
fields:
- name: layout
  type: text
  config:
    required: false
  label: layout
  description: Provide a layout for this page
  default: blocks-layout
- name: title
  type: text
  config:
    required: false
  label: title
  description: Provide a title for this page
- name: season
  type: number
  label: season
  description: 'When was this project completed? (Ex: 2018 - Season 4)'
  default: '4'
  required: true
  config:
    min: '1'
    max: '4'
    step: 
- name: category
  type: tag_list
  default:
  - website
  - " content"
  label: category
- name: seo-description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: seo description
  description: Provide the description of the page for SEO purposes
- name: seo-keywords
  type: tag_list
  default:
  - manage my brand
  - brand consulting
  - production work
  - business strategy
  label: seo keywords
  description: Provide keywords for this page for SEO purposes.
