---
label: BLOCK-META
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: false
  label: layout
- name: title
  type: text
  config:
    required: false
  label: title
- name: season
  type: number
  label: season
  description: ''
  default: 0
  required: true
  config:
    min: '1'
    max: '4'
    step: 
- name: category
  type: tag_list
  default:
  - website
  - " content"
  label: category
- name: seo-description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: seo description
- name: seo-keywords
  type: tag_list
  default:
  - manage my brand
  - brand consulting
  - production work
  - business strategy
  label: seo keywords
